[wallet]
mnemonic = ""
count = 50
keys = []

[network]
rpc = [
    # devnet
    "https://api.devnet.solana.com",
    # testnet
    "https://api.testnet.solana.com",
    # mainnet-beta
    "https://api.mainnet-beta.solana.com/"
]

sleep = 2000